real test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,7 +28,7 @@ jobs:
     timeout-minutes: 30
 
     outputs:
-      image: ${{ steps.build-upload.outputs.image }}
+      image: ${{ steps.bake_metadata.outputs.image }}
 
     steps:
       - name: Checkout Repo ⚡️
@@ -75,7 +75,7 @@ jobs:
       - name: Set output variables
         id: bake_metadata
         run: |
-            .github/workflows/extract-image-names.sh | tee -a "${GITHUB_OUTPUT}"
+            .github/workflows/extract-image-name.sh | tee -a "${GITHUB_OUTPUT}"
         env:
             BAKE_METADATA: ${{ steps.build-upload.outputs.metadata }}
 
@@ -96,13 +96,27 @@ jobs:
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: pull image from ghcr.io
-        run: docker pull ${{ needs.build.outputs.image}}
+      - name: Run container checking libraries exist in the container
+        run: |
+          docker run --rm ${{ needs.build.outputs.image }} /bin/bash -c "ls -l /usr/local" > /tmp/ls-l.txt
+          if grep -q libxc /tmp/ls-l.txt; then
+              echo "libxc found"
+          else
+              echo "libxc not found"
+              exit 1
+          fi
+
+          if grep -q lapack /tmp/ls-l.txt; then
+              echo "lapack found"
+          else
+              echo "lapack not found"
+              exit 1
+          fi
 
   publish:
       runs-on: ubuntu-latest
       timeout-minutes: 30
-      needs: test
+      needs: [build, test]
       strategy:
         matrix:
           registry: ["docker.io", "ghcr.io"]
@@ -156,7 +170,7 @@ jobs:
         - name: Push image
           uses: akhilerm/tag-push-action@v2.2.0
           with:
-              src: ${{ steps.images.outputs.src }}
+              src: ${{ needs.build.outputs.image }}
               dst: ${{ steps.meta.outputs.tags }}
 
         - name: Docker Hub Description
@@ -165,5 +179,5 @@ jobs:
           with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
-              repository: aiidalab/${{ matrix.target }}
+              repository: pspgen/build-machine
               short-description: ${{ github.event.repository.description }}
